server:
  port: 8082

spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${service.url.keycloak}/realms/twitter-clone

# service-url 
service:
  url:
    keycloak: http://localhost:8085