server:
  port: 8081

spring:
  application:
    name: tweet-service
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://localhost:5432/twt_tweetservice
    username: postgres
    password: q
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: none
  liquibase:
    change-log: '/changelogs/changelog-master.xml'