server:
  port: 8081

spring:
  application:
    name: tweet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/twt_tweetservice
    username: postgres
    password: q
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${service.url.keycloak}/realms/twitter-clone
  liquibase:
    change-log: '/changelogs/changelog-master.xml'

# service-url
service:
  url:
    keycloak: http://localhost:8085