server:
  port: 8081

spring:
  application:
    name: tweet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/twt_tweetservice
    username: postgres
    password: q
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
