pipeline {
    agent any
    stages {
        stage('[Backend] Prepare build agent') {
            agent {
                docker {
                    image 'maven:3.8.4-openjdk-17'
                    args '-v /var/run/docker.sock:/var/run/docker.sock -v /home/twitter-clone/.m2:/root/.m2 -u root:root'
                    reuseNode true
                }
            }
            stages {
                stage('[Backend] Build') {
                    steps {
                        sh './mvnw compile'
                    }
                }
            }
        }
    }
}
